### ISSUE TITLE
ChiBE won't start, help please?

### ISSUE THREAD

**Issue by lczqd** [PathwayCommons/chibe#72]
My system is windows 7 (64bit). 
I have JAVA 8.
I installed chibe-2.2.0-setup-win32-win32-x86_64.msi.
But when I run ChiBE_win64.exe, nothing happens.
Anyone who can help me with this?
Many thanks.

**Comment by IgorRodchenkov** [comment]
Let's ask @ozgunbabur ...

But I suspect ChiBE still does not work with Java 7 or 8 (on Macs at least); the [user guide](http://www.cs.bilkent.edu.tr/~ivis/chibe/ChiBE-2.2.UG.pdf) refers to [this](https://code.google.com/archive/p/chibe/), which says:
`Note: ChiBE cannot run on Mac OS X with Java 1.7. This is because Apple decided to remove 32-bit support from Java 1.7. We recommend using Java 1.6 with Mac OS X. Here is how to do it.`

PS:
Also I wonder how comes there was v2.2 release, but there is no such tag or release message in this repo?

**Comment by lczqd** [comment]
@IgorRodchenkov 

Thank you for the information.

Sorry I can not open the link https://code.google.com/archive/p/chibe/ here from China. 
In the directory where I installed ChiBE a file JRE.rtf gives the following information:
"In order to use ChiBE-2.2.0, JRE 6 (Java Runtime Environment) or higher must be installed." 

So, I should degrade JAVA 8 to JRE 6?

**Comment by lczqd** [comment]
Solved it!
I installed JRE 8 from http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html.
and CHiBE works.
What is the different between JAVA 8 and JRE 8?

**Comment by ozgunbabur** [comment]
Hi Iczqd, I am glad you solved it. Sorry I couldn't write a reply because I
couldn't get a Windows machine to try it.

It doesn't matter if you use JRE or JDK, but it may matter if you use
Oracle JVM or other JVM. We used Oracle during development. ChiBE was built
on Eclipse graph drawing library, which is platform dependent. They have
different libraries for even different architectures. It is possible that
it would not work with all JVMs.

**Comment by lczqd** [comment]
@ozgunbabur 

Hi, ozgun.
I see. 
Thank you for this information. Maybe it will be helpful to mention this in the Readme or User's guide.

Best regards.
